{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\tqdm\\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html\n",
      "  from .autonotebook import tqdm as notebook_tqdm\n"
     ]
    }
   ],
   "source": [
    "from fastapi import FastAPI\n",
    "from llama_index.embeddings.sagemaker_endpoint import SageMakerEmbedding\n",
    "from llama_index.core import StorageContext, Document, VectorStoreIndex\n",
    "from llama_index.vector_stores.weaviate import WeaviateVectorStore\n",
    "import weaviate\n",
    "from llama_index.core.memory import ChatMemoryBuffer\n",
    "from llama_index.core.node_parser import SimpleNodeParser\n",
    "\n",
    "from llama_index.llms.ollama import Ollama"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\weaviate\\warnings.py:121: DeprecationWarning: Dep005: You are using weaviate-client version 3.26.2. The latest version is 4.5.7.\n",
      "            Please consider upgrading to the latest version. See https://weaviate.io/developers/weaviate/client-libraries/python for details.\n",
      "  warnings.warn(\n"
     ]
    }
   ],
   "source": [
    "app = FastAPI()\n",
    "\n",
    "\n",
    "client = weaviate.Client(\"http://localhost:8080\")\n",
    "\n",
    "AWS_ACCESS_KEY_ID = \"\"\n",
    "AWS_SECRET_ACCESS_KEY = \"\"\n",
    "REGION_NAME = \"eu-central-1\"\n",
    "\n",
    "# Initialize Weaviate vector store\n",
    "vector_store = WeaviateVectorStore(\n",
    "    weaviate_client=client, index_name=\"LlamaIndex\"\n",
    ")\n",
    "\n",
    "# Initialize embedding model\n",
    "embed_endpoint_model = SageMakerEmbedding(\n",
    "    endpoint_name=\"BGE-M3\",\n",
    "    aws_access_key_id=AWS_ACCESS_KEY_ID,\n",
    "    aws_secret_access_key=AWS_SECRET_ACCESS_KEY,\n",
    "    region_name=REGION_NAME,\n",
    ")\n",
    "\n",
    "# Initialize storage context\n",
    "storage_context = StorageContext.from_defaults(vector_store=vector_store)\n",
    "\n",
    "# Initialize index\n",
    "index = None\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "@app.post(\"/index-data/\")\n",
    "async def index_data(data: list[dict]):\n",
    "    global index\n",
    "    \n",
    "    documents = [Document(**doc) for doc in data]\n",
    "    parser = SimpleNodeParser.from_defaults(chunk_size=1024)\n",
    "    nodes = parser.get_nodes_from_documents(documents)\n",
    "    index = VectorStoreIndex(\n",
    "            nodes, storage_context=storage_context, embed_model=embed_endpoint_model\n",
    "        )\n",
    "\n",
    "        #index.add_documents(documents)\n",
    "    \n",
    "    return {\"message\": \"Data indexed successfully\"}\n",
    "\n",
    "\n",
    "@app.post(\"/query-data/\")\n",
    "async def query_data(query: str):\n",
    "    if index is None:\n",
    "        return {\"error\": \"Index is not initialized. Please index data first.\"}\n",
    "    \n",
    "    llm = Ollama(base_url=\"https://n3iipm5bkl.execute-api.eu-central-1.amazonaws.com\", model=\"mistral\")\n",
    "    query_engine = index.as_query_engine(llm=llm)\n",
    "    response = query_engine.query(query)\n",
    "    \n",
    "    return response\n",
    "\n",
    "\n",
    "@app.post(\"/chat-with-data/\")\n",
    "async def chat_data(query: str):\n",
    "    if index is None:\n",
    "        return {\"error\": \"Index is not initialized. Please index data first.\"}\n",
    "    \n",
    "    llm = Ollama(base_url=\"https://n3iipm5bkl.execute-api.eu-central-1.amazonaws.com\", model=\"mistral\")\n",
    "    memory = ChatMemoryBuffer.from_defaults()\n",
    "    query_engine = index.as_query_engine(llm=llm,memory=memory)\n",
    "    response = query_engine.query(query)\n",
    "    \n",
    "    return response\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO:     Started server process [19312]\n",
      "INFO:     Waiting for application startup.\n",
      "INFO:     Application startup complete.\n",
      "INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "INFO:     127.0.0.1:55062 - \"POST /index-data/ HTTP/1.1\" 200 OK\n",
      "INFO:     127.0.0.1:55072 - \"POST /query-data/?query=Can%20you%20list%20the%20names%20of%20all%20individuals%3F HTTP/1.1\" 200 OK\n",
      "INFO:     127.0.0.1:55073 - \"POST /query-data/?query=What%20are%20the%20occupations%20of%20individuals%20from%20New%20York%3F HTTP/1.1\" 200 OK\n",
      "INFO:     127.0.0.1:55086 - \"POST /query-data/?query=Who%20is%20the%20youngest%20person%20%3F HTTP/1.1\" 500 Internal Server Error\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\httpx\\_transports\\default.py\", line 69, in map_httpcore_exceptions\n",
      "    yield\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\httpx\\_transports\\default.py\", line 233, in handle_request\n",
      "    resp = self._pool.handle_request(req)\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\httpcore\\_sync\\connection_pool.py\", line 216, in handle_request\n",
      "    raise exc from None\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\httpcore\\_sync\\connection_pool.py\", line 196, in handle_request\n",
      "    response = connection.handle_request(\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\httpcore\\_sync\\connection.py\", line 99, in handle_request\n",
      "    raise exc\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\httpcore\\_sync\\connection.py\", line 76, in handle_request\n",
      "    stream = self._connect(request)\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\httpcore\\_sync\\connection.py\", line 154, in _connect\n",
      "    stream = stream.start_tls(**kwargs)\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\httpcore\\_backends\\sync.py\", line 152, in start_tls\n",
      "    with map_exceptions(exc_map):\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\contextlib.py\", line 153, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\httpcore\\_exceptions.py\", line 14, in map_exceptions\n",
      "    raise to_exc(exc) from exc\n",
      "httpcore.ConnectTimeout: _ssl.c:980: The handshake operation timed out\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\uvicorn\\protocols\\http\\h11_impl.py\", line 407, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\uvicorn\\middleware\\proxy_headers.py\", line 69, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fastapi\\applications.py\", line 1054, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\starlette\\applications.py\", line 123, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 186, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 164, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 65, in __call__\n",
      "    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\starlette\\_exception_handler.py\", line 64, in wrapped_app\n",
      "    raise exc\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\starlette\\routing.py\", line 756, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\starlette\\routing.py\", line 776, in app\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\starlette\\routing.py\", line 297, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\starlette\\routing.py\", line 77, in app\n",
      "    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\starlette\\_exception_handler.py\", line 64, in wrapped_app\n",
      "    raise exc\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\starlette\\routing.py\", line 72, in app\n",
      "    response = await func(request)\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fastapi\\routing.py\", line 278, in app\n",
      "    raw_response = await run_endpoint_function(\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fastapi\\routing.py\", line 191, in run_endpoint_function\n",
      "    return await dependant.call(**values)\n",
      "  File \"C:\\Users\\abdel\\AppData\\Local\\Temp\\ipykernel_19312\\640143373.py\", line 24, in query_data\n",
      "    response = query_engine.query(query)\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\llama_index\\core\\instrumentation\\dispatcher.py\", line 274, in wrapper\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\llama_index\\core\\base\\base_query_engine.py\", line 53, in query\n",
      "    query_result = self._query(str_or_query_bundle)\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\llama_index\\core\\instrumentation\\dispatcher.py\", line 274, in wrapper\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\llama_index\\core\\query_engine\\retriever_query_engine.py\", line 190, in _query\n",
      "    response = self._response_synthesizer.synthesize(\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\llama_index\\core\\instrumentation\\dispatcher.py\", line 274, in wrapper\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\llama_index\\core\\response_synthesizers\\base.py\", line 242, in synthesize\n",
      "    response_str = self.get_response(\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\llama_index\\core\\instrumentation\\dispatcher.py\", line 274, in wrapper\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\llama_index\\core\\response_synthesizers\\compact_and_refine.py\", line 43, in get_response\n",
      "    return super().get_response(\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\llama_index\\core\\instrumentation\\dispatcher.py\", line 274, in wrapper\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\llama_index\\core\\response_synthesizers\\refine.py\", line 183, in get_response\n",
      "    response = self._give_response_single(\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\llama_index\\core\\response_synthesizers\\refine.py\", line 238, in _give_response_single\n",
      "    program(\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\llama_index\\core\\response_synthesizers\\refine.py\", line 84, in __call__\n",
      "    answer = self._llm.predict(\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\llama_index\\core\\instrumentation\\dispatcher.py\", line 274, in wrapper\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\llama_index\\core\\llms\\llm.py\", line 430, in predict\n",
      "    chat_response = self.chat(messages)\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\llama_index\\core\\llms\\callbacks.py\", line 144, in wrapped_llm_chat\n",
      "    f_return_val = f(_self, messages, **kwargs)\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\llama_index\\llms\\ollama\\base.py\", line 101, in chat\n",
      "    response = client.post(\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\httpx\\_client.py\", line 1145, in post\n",
      "    return self.request(\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\httpx\\_client.py\", line 827, in request\n",
      "    return self.send(request, auth=auth, follow_redirects=follow_redirects)\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\httpx\\_client.py\", line 914, in send\n",
      "    response = self._send_handling_auth(\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\httpx\\_client.py\", line 942, in _send_handling_auth\n",
      "    response = self._send_handling_redirects(\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\httpx\\_client.py\", line 979, in _send_handling_redirects\n",
      "    response = self._send_single_request(request)\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\httpx\\_client.py\", line 1015, in _send_single_request\n",
      "    response = transport.handle_request(request)\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\httpx\\_transports\\default.py\", line 232, in handle_request\n",
      "    with map_httpcore_exceptions():\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\contextlib.py\", line 153, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"c:\\Users\\abdel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\httpx\\_transports\\default.py\", line 86, in map_httpcore_exceptions\n",
      "    raise mapped_exc(message) from exc\n",
      "httpx.ConnectTimeout: _ssl.c:980: The handshake operation timed out\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "INFO:     127.0.0.1:55087 - \"POST /query-data/?query=Who%20is%20the%20youngest%20individual%20%3F HTTP/1.1\" 200 OK\n",
      "INFO:     127.0.0.1:55096 - \"POST /query-data/?query=Who%20is%20the%20youngest%20individual%20%3F HTTP/1.1\" 200 OK\n",
      "INFO:     127.0.0.1:55115 - \"POST /query-data/?query=List%20all%20individuals%20over%20the%20age%20of%2030%20 HTTP/1.1\" 200 OK\n",
      "INFO:     127.0.0.1:55125 - \"POST /chat-with-data/?query=Who%20is%20the%20software%20engineer%20from%20New%20York%3F HTTP/1.1\" 200 OK\n",
      "INFO:     127.0.0.1:55127 - \"POST /chat-with-data/?query=How%20old%20is%20John%20Doe%3F HTTP/1.1\" 200 OK\n"
     ]
    }
   ],
   "source": [
    "import asyncio\n",
    "import uvicorn\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    config = uvicorn.Config(app)\n",
    "    server = uvicorn.Server(config)\n",
    "    await server.serve()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
